-- AlterTable
ALTER TABLE "Recipe" ADD COLUMN "emoji" TEXT;
ALTER TABLE "Recipe" ADD COLUMN "imageUrl" TEXT;
ALTER TABLE "Recipe" ADD COLUMN "imageAlt" TEXT;
ALTER TABLE "Recipe" ADD COLUMN "difficulty" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Recipe" ADD COLUMN "isFavorite" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Recipe" ADD COLUMN "referenceUrl" TEXT;
ALTER TABLE "Recipe" ADD COLUMN "servings" INTEGER;
ALTER TABLE "Recipe" ADD COLUMN "memoMarkdown" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Recipe" ADD COLUMN "savedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "ShoppingItem" ADD COLUMN "purchased" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "ShoppingItem" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
